addons:
  firefox: latest

before_install:
  - docker pull selenium/standalone-firefox:2.53.0
  - docker run -d -p 127.0.0.1:4455:4444 selenium/standalone-firefox:2.53.0


#script:
#  - R -f inst/app/tests/run_shinyTest.R
# only report coverage for the release version
after_success:
  - docker stop $(docker ps -a -q)


jobs:
  include:
  - stage : "Test"
name : "TestThat"
script : test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'devtools::install(); covr::codecov()'

